#!/bin/sh

DOCKER_TAG="$1"

docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" \
  && docker build -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$DOCKER_TAG . \
  && docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$DOCKER_TAG
