#!/bin/sh

ZOONAV_VERSION="$1"

docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" \
  && docker build -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$ZOONAV_VERSION . \
  && docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$ZOONAV_VERSION
